FROM node:18.17.1

WORKDIR /app

COPY . .

RUN npm config set registry https://registry.npm.taobao.org/

RUN yarn

ENTRYPOINT [ "yarn"]

CMD ["start"]


# 构建并运行，但不保存镜像（适用于一次性测试）
# podman run --rm $(podman build -q .)
